### ISSUE TITLE
ValueError in regression tasks

### ISSUE THREAD

**Issue by amin-sagar** [IBM/AutoPeptideML#54]
Hello.
I am trying to run a regression task using the non-canonical binding dataset available at https://github.com/IBM/PeptideGeneralizationBenchmarks/tree/main/downstream_data

I have tried other datasets as well but for all regression tasks I get 
```
context = ' by KBinsDiscretizer'                                                                   │                 │
│ │                       copy = False                                                                                    │                 │
│ │                      dtype = None                                                                                     │                 │
│ │              dtype_numeric = True                                                                                     │                 │
│ │                 dtype_orig = dtype('float64')                                                                         │                 │
│ │                dtypes_orig = None                                                                                     │                 │
│ │                  ensure_2d = True                                                                                     │                 │
│ │          ensure_all_finite = True                                                                                     │                 │
│ │        ensure_min_features = 1                                                                                        │                 │
│ │         ensure_min_samples = 1                                                                                        │                 │
│ │        ensure_non_negative = False                                                                                    │                 │
│ │                  estimator = KBinsDiscretizer(encode='ordinal', n_bins=10)                                            │                 │
│ │             estimator_name = 'KBinsDiscretizer'                                                                       │                 │
│ │           force_all_finite = 'deprecated'                                                                             │                 │
│ │            force_writeable = False                                                                                    │                 │
│ │                 input_name = 'X'                                                                                      │                 │
│ │     is_array_api_compliant = False                                                                                    │                 │
│ │                        msg = 'Expected 2D array, got 1D array instead:\narray=[10.812479 11.075721  5.        4'+3119 │                 │
│ │                      order = None                                                                                     │                 │
│ │ pandas_requires_conversion = False                                                                                    │                 │
│ │             type_if_series = None                                                                                     │                 │
│ │                         xp = <sklearn.utils._array_api._NumPyAPIWrapper object at 0x7c7a3f53dd30>  
ValueError: Expected 2D array, got 1D array instead:

Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

```
Here is my config file
```
databases:
  dataset:
    feat_fields: SMILES
    label_field: labels
    path: ./nc-binding.csv
    verbose: false
outputdir: ./results
pipeline:
  aggregate: true
  elements:
  - pipe-smiles-input:
      aggregate: false
      elements:
      - filter-smiles: {}
      name: smiles-input
      verbose: false
  - pipe-seq-input:
      aggregate: false
      elements:
      - filter-smiles:
          keep_smiles: false
      - canonical-cleaner:
          substitution: G
      - sequence-to-smiles: {}
      name: seq-input
      verbose: false
  name: macromolecules_pipe
  verbose: false
representation:
  elements:
  - chemberta-2:
      average_pooling: true
      batch_size: 32
      device: cpu
      engine: lm
      model: chemberta-2
  - molformer-xl:
      average_pooling: true
      batch_size: 32
      device: cpu
      engine: lm
      model: molformer-xl
  - ecfp-counts-16:
      engine: fp
      fp: ecfp-count
      nbits: 2048
      radius: 8
  verbose: true
test:
  algorithm: ccpart
  filter: 0.185
  min_threshold: 0.1
  partitions: all
  sim_arguments:
    bits: 1024
    data_type: molecule
    field_name: SMILES
    min_threshold: 0.1
    radius: 4
    sim_function: jaccard
    verbose: 2
  threshold_step: 0.1
  verbose: 2
train:
  hspace:
    models:
      elements:
        lightgbm:
          colsample_bytree:
            log: false
            max: 1.0
            min: 0
            type: float
          learning_rate:
            log: true
            max: 0.1
            min: 1.0e-07
            type: float
          max_depth:
            log: false
            max: 10
            min: 3
            type: int
          min_split_gain:
            log: true
            max: 0.001
            min: 1.0e-10
            type: float
          n_estimators:
            log: false
            max: 1000
            min: 10
            type: int
          num_leaves:
            log: false
            max: 1024
            min: 8
            type: int
          reg_alpha:
            log: true
            max: 0.001
            min: 1.0e-10
            type: float
          subsample:
            log: false
            max: 1.0
            min: 0.5
            type: float
          verbose:
            type: fixed
            value: -1
        rf:
          ccp_alpha:
            log: true
            max: 0.001
            min: 1.0e-10
            type: float
          min_samples_split:
            log: false
            max: 100
            min: 2
            type: int
          n_estimators:
            log: false
            max: 1000
            min: 10
            type: int
      type: ensemble
    representations:
    - chemberta-2
    - molformer-xl
    - ecfp-counts-16
  optim_strategy:
    direction: minimize
    metric: mse
    n_jobs: 16
    n_steps: 100
    partition: random
    patience: 20
    task: reg
    trainer: optuna
  task: reg
val:
  k: 10
  random_state: 1
  type: kfold

```
Could you think of any reasons for this error? I would be really grateful for any suggestions. 
Best,
Amin.
